### ISSUE TITLE
Generator problem

### ISSUE THREAD

**Issue by Rchramos** [SarmadTanveer/EDSIM#8]
There is an error occurring in lines 56 and 80 of ED_Model

**Comment by SarmadTanveer** [comment]
see branch issue_5_fix for solution. Your problem is not the patient generator, every time you call env.process(emergencyDepartmentProcess(ab)), env.process expects a generator. You did not provide it a generator. See last commit for additions.

**Comment by Rchramos** [comment]
Thanks
It is running now 
Next I will try to add priority to the resources
